-- Seed generado desde la hoja LISTADO del archivo BITACORA ENTRADA Y SALIDA DE VISITANTES.xlsx

INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Abraham Escamilla', NULL, NULL, 'abraham escamilla', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Abraham Vázquez Hernández', NULL, NULL, 'abraham vázquez hernández', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Alba Escobar Romero', NULL, NULL, 'alba escobar romero', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Alejandra Sosa Solís', NULL, NULL, 'alejandra sosa solís', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Alma Karina Medina Lara', NULL, NULL, 'alma karina medina lara', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Ana Venegas López', NULL, NULL, 'ana venegas lópez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Andrea Galvan Chaire', NULL, NULL, 'andrea galvan chaire', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Ángeles Martinez Garcia', NULL, NULL, 'ángeles martinez garcia', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Angelica Rangel Longoria', NULL, NULL, 'angelica rangel longoria', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Cesar Naranjo Moreno', NULL, NULL, 'cesar naranjo moreno', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Claudia Loa Gonzalez', NULL, NULL, 'claudia loa gonzalez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Comercial', NULL, NULL, 'comercial', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Contabilidad', NULL, NULL, 'contabilidad', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Diego Irving Hernández Cenobio', NULL, NULL, 'diego irving hernández cenobio', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Dr. Victor David Mena Aguilar', NULL, NULL, 'dr. victor david mena aguilar', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Dulce Villegas', NULL, NULL, 'dulce villegas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Edgar Noriega Torres', NULL, NULL, 'edgar noriega torres', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Eduardo Cervantes Hernandez', NULL, NULL, 'eduardo cervantes hernandez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Eduardo Villareal Obregón', NULL, NULL, 'eduardo villareal obregón', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Elena Jazmin Ortega Vergara', NULL, NULL, 'elena jazmin ortega vergara', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Fernando Caviedes Avalos', NULL, NULL, 'fernando caviedes avalos', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Fidel Téllez', NULL, NULL, 'fidel téllez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Finanzas', NULL, NULL, 'finanzas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Francisco Iván Sánchez Zúñiga', NULL, NULL, 'francisco iván sánchez zúñiga', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Ing. Victor Farid Mena Nader', NULL, NULL, 'ing. victor farid mena nader', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Iraís Morales Montesino', NULL, NULL, 'iraís morales montesino', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Javier Olmedo Hernandez', NULL, NULL, 'javier olmedo hernandez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Joel Froylan Andres Vega Molina', NULL, NULL, 'joel froylan andres vega molina', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Jorge Luis Campos Araujo', NULL, NULL, 'jorge luis campos araujo', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('José Maria Zarate Rayas', NULL, NULL, 'josé maria zarate rayas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Julia Gonzalez Morales', NULL, NULL, 'julia gonzalez morales', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Jurídico', NULL, NULL, 'jurídico', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Karen Alexa Hernández', NULL, NULL, 'karen alexa hernández', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Karla Karina Vassallo Esponda', NULL, NULL, 'karla karina vassallo esponda', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Leonardo Ruelas Castañón', NULL, NULL, 'leonardo ruelas castañón', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Leonor Espinosa', NULL, NULL, 'leonor espinosa', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Liliana Ríos Sanchez', NULL, NULL, 'liliana ríos sanchez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Lissete Martinez Blas', NULL, NULL, 'lissete martinez blas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Luis Alejandro Paredes Arzate', NULL, NULL, 'luis alejandro paredes arzate', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Luis Gael Ortega Ríos', NULL, NULL, 'luis gael ortega ríos', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Luis López', NULL, NULL, 'luis lópez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Marco Antonio Río de la Loza Gomez', NULL, NULL, 'marco antonio río de la loza gomez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Margarita Cortés Ruiz', NULL, NULL, 'margarita cortés ruiz', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Maria del Carmen Basaldua Olvera', NULL, NULL, 'maria del carmen basaldua olvera', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Maria Teresa Bautista Melgarejo', NULL, NULL, 'maria teresa bautista melgarejo', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Mariana Gonzalez Hernández', NULL, NULL, 'mariana gonzalez hernández', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Mariana Robles Patiño', NULL, NULL, 'mariana robles patiño', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Mario Piña Bahena', NULL, NULL, 'mario piña bahena', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Mayra Garcia Cano', NULL, NULL, 'mayra garcia cano', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Miguel Angel Avila Requena', NULL, 'mavila@drt.com.mx', 'miguel angel avila requena mavila avila requena', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Mónica Bautista', NULL, NULL, 'mónica bautista', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Montserrat Ponce Ortega', NULL, NULL, 'montserrat ponce ortega', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Nancy Sedot Albarrán Muñoz', NULL, NULL, 'nancy sedot albarrán muñoz', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Natalia Jimenez Rivera', NULL, NULL, 'natalia jimenez rivera', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Natalia Zaldívar Águila', NULL, NULL, 'natalia zaldívar águila', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Nayely Marisol Sánchez Mojica', NULL, NULL, 'nayely marisol sánchez mojica', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Paola Escobedo Galvan', NULL, NULL, 'paola escobedo galvan', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Proyectos', NULL, NULL, 'proyectos', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Recursos Humanos', NULL, NULL, 'recursos humanos', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Ricardo Salazar Muro', NULL, NULL, 'ricardo salazar muro', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Romel Eduardo Islas Hernandez', NULL, NULL, 'romel eduardo islas hernandez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Rosario Ramírez Ramírez', NULL, NULL, 'rosario ramírez ramírez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Rosy Alanís Correa', NULL, NULL, 'rosy alanís correa', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Sistemas', NULL, NULL, 'sistemas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Valeria Cano Cárdenas', NULL, NULL, 'valeria cano cárdenas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Ventas', NULL, NULL, 'ventas', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Violeta Olvera Martinez', NULL, NULL, 'violeta olvera martinez', 'ACTIVE');
INSERT INTO ra_hosts (full_name, area_name, email, search_alias, status) VALUES ('Yocelin Moya Echeverria', NULL, NULL, 'yocelin moya echeverria', 'ACTIVE');
